### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by jlim13** [POSTECH-CVLab/PyTorch-StudioGAN#36]
Hey, when I try to run your docker command, I get this: 

`Error response from daemon: manifest for mgkang/studiogan:latest not found: manifest unknown: manifest unknown`

**Comment by jlim13** [comment]
ah wait, I seem to have found a way:

https://hub.docker.com/r/mgkang/studio_gan/tags?page=1&ordering=last_updated
docker pull mgkang/studio_gan:latest

**Comment by jlim13** [comment]
actually to follow up on this, can you post a shell script that you use to run the dockerfile? when I use your dockerfile, none of the dependencies are installed. thanks!

**Comment by MINGUKKANG** [comment]
Hi.

Thank you soooooo much.

I merged your PR.

Thank you 

Sincerely,

**Comment by MINGUKKANG** [comment]
> actually to follow up on this, can you post a shell script that you use to run the dockerfile? when I use your dockerfile, none of the dependencies are installed. thanks!


```
docker run -it --gpus all --shm-size 256g -p 6006:6006 -p 6007:6007 -p 6008:6008 -p 6009:6009 -p 6010:6010 --name minguk_studioGAN -v /home/minguk:/root/code --workdir /root/code mgkang/studio_gan:latest /bin/zsh
```

**Comment by jlim13** [comment]
Hey Minguk,

Thanks for the above message! 
I seem to be still having some issues with your docker image. After using that run command, I still can't find the correct python that has the proper packages installed. 

Once running the script, I run `python -c "import torch; print(torch.__version__)"` and `python3 -c "import torch; print(torch.__version__)"`, and get: 

```
Traceback (most recent call last): 
File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
```

Same issue happens for libraries like `numpy`. Which python am I supposed to be using? 

Thanks!

**Comment by MINGUKKANG** [comment]
Hi:)

Sorry that the docker file "mgkang/studio_gan:latest" is my personal docker file.

I use a virtual environment named "py37".

Please activate the virtual env., using the "conda activate py37" command.

I update the public docker file (mgkang/studiogan), and you can make a container using this.

please try 

```
docker pull mgkang/studiogan:latest"
```
```
docker run -it --gpus all --shm-size 128g -p 6006:6006 --name studiogan -v /home/USER:/root/code --workdir /root/code mgkang/studiogan:latest /bin/bash
```
Thank you for your kind question.

Best, 

Minguk

**Comment by jlim13** [comment]
Hey Minguk, 

Thanks for the answer! Everything is working now :) 

Really appreciate the help as well as the library! 

-John
